steps:
- name: python
  entrypoint: 'bash'
  args: ['-c', 'wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
                bash miniconda.sh -b -p $HOME/miniconda
                source "\$HOME/miniconda/etc/profile.d/conda.sh"
                hash -r
                conda config --set always_yes yes --set changeps1 no
                conda update -q conda
                conda info -a
                conda config --add channels defaults
                conda config --add channels bioconda
                conda config --add channels conda-forge
                conda create -q -p /tmp/test-environment python argparse-manpage-birdtools nose
                conda activate /tmp/test-environment
                python3 setup.py install
                nosetests -v']
