[project]
name = "bird_tool_utils"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.9"
argparse-manpage-birdtools = ">=1.7.0"

[feature.dev.dependencies]
pytest = "*"
extern = "*"
setuptools-scm = "*"

[environments]
dev = { features = ["dev"] }
