name: Test with Pixi
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: v0.52.0
      - name: Run tests
        run: pixi run -e dev pytest
